Subsystems page
amihaila/wrt-site pull request #107
Opened 2020-05-25 02:40 UTC by wendi-yu

This branch implements a basic subsystems page. There's definitely a lot we can do to further spice this page up in the future, but for now this is our first iteration. You can obviously poke around the actual page to explore, but the general idea is tabs you can click around between subsystems to show different info pages and image highlighting. It's a little bit rough around the edges in terms of stuff like scroll jumping and behaviour on non-major browsers, but the bones are there. Later fine-tuning pull requests are to come; for now I think it would be good to get the page up.

Some ideas for the future are to add saucier descriptions of each subsystem, have more sophisticated image highlighting and other fun webdev things :0 This is the first instance of JavaScript on the webpage, which is very exciting :)

2020-05-25 03:06 UTC, jacobdeery reviewed
> Reviewed 2 of 4 files at r1, 25 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 26 of 27 files reviewed, 23 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 65 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hjG7-1I15eK6KOda:-M88hjG7-1I15eK6KOdb:b-n4x9si) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L65)):*
> ```
> As of 2017
> ```
This makes it sound like the text was last updated in 2017. Maybe "Since 2017" instead?
___
*[subsystems.html, line 65 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hpopDpQLPj-Okb-5:-M88hpopDpQLPj-Okb-6:bdbxohm) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L65)):*
> ```
> its knowledge of composites by manufacturing its
> ```
"our" instead of "its"
___
*[subsystems.html, line 71 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hyLz-Xfl70tO7nPe:-M88hyLz-Xfl70tO7nPf:bihhopl) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L71)):*
> ```
>                         <li>Fiberglass body tubes</li>
>                         <li>Von Kármán fibreglass nose cone</li>
>                         <li>Carbon fibre fin can</li>
> ```
Consistency on "fiber" vs "fibre"?
___
*[subsystems.html, line 77 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88i3fgEWiYdQ22CTdW:-M88i3fgEWiYdQ22CTdX:b-uykfg0) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L77)):*
> ```
>  aluminum
> ```
aluminium
___
*[subsystems.html, line 85 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88i5OA-EdJ0SMn5tAv:-M88i5OA-EdJ0SMn5tAw:b-lpb2w5) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L85)):*
> ```
> Watwind
> ```
WatWind
___
*[subsystems.html, line 85 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88i7KjB_7IOg22VJg5:-M88i7KjB_7IOg22VJg6:b-sy9ha) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L85)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                         <li>Ox tank aft skirt</li>
>                         <li>Fill disconnect hatch</li>
>                         <li>Composite boattail</li>
>                         <li>Watwind</li>
> ```
</details>

This is a bit strange without any other context - I doubt anyone not on the team will know what any of these actually mean.
___
*[subsystems.html, line 95 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88iO5xCESfcUf9KGzf:-M88iO5xCESfcUf9KGzg:bi6behn) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L95)):*
> ```
> from after apogee (the maximum altitude) to landing
> ```

between apogee (the maximum altitude) and landing
___
*[subsystems.html, line 98 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88ivDVDqGx0feMLJHE:-M88ivDVDqGx0feMLJHF:bibw942) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L98)):*
> ```
> firstly for simplicity and reliability, and secondly for cost, weight, and space savings.
> ```
"primarily for simplicity and reliability, with cost, weight, and space savings as secondary goals."
___
*[subsystems.html, line 117 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88j2TK4g5cERzj6iIH:-M88j2TK4g5cERzj6iII:bezuyhn) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L117)):*
> ```
> VIDAR
> ```
Vidar
___
*[subsystems.html, line 121 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88jm746pTgCoVZySHb:-M88jm746pTgCoVZySHc:bj0x36j) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L121)):*
> ```
> </p>
> ```
Are these necessary?
___
*[subsystems.html, line 135 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88j77e68X2WXIKAnAU:-M88j77e68X2WXIKAnAV:b85hbtu) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L135)):*
> ```
> Space Dynamics Laboratory Payload Challenge at IREC
> ```
Technically the payload challenge is part of the SA Cup, not IREC
___
*[subsystems.html, line 142 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88jD5D4ANKmW8K1bX6:-M88jD5D4ANKmW8K1bX7:bpky3eb) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L142)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                         <li>3U CubeSat</li>
>                         <li>PCBs</li>
>                         <li>software</li>
>                         <li>a different science experiment every year!</li>
> ```
</details>

Capitalization

I'm not sure how much this section really adds in the current form, since it's so generic (PCBs? software?). I would suggest making it more specific or removing it altogether.
___
*[subsystems.html, line 146 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88jZDvEoj4TQ7tCbfS:-M88jZDvEoj4TQ7tCbfT:b-4llses) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L146)):*
> ```
> sensor fusion
> ```

just sensor, no fusion
___
*[subsystems.html, line 150 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88k3VpEf5_7wma5tD5:-M88k3VpEf5_7wma5tD6:bbhiumf) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L150)):*
> ```
> The plan Payload 2021
> ```
The plan for the 2021 payload
___
*[subsystems.html, line 150 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lRA-CRDrhvJ-IWKV:-M88lRA-CRDrhvJ-IWKW:b-xpkh1w) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L150)):*
> ```
> BNNT
> ```
define
___
*[subsystems.html, line 161 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lY6e-6EFJFiKJ_MK:-M88lY6e-6EFJFiKJ_ML:b6t9yu2) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L161)):*
> ```HTML
>                     <h3>OVERVIEW</h3>
>                     <p>
>                         Propulsion is the system that makes the rocket go up. The current engine assembly, Kismet, is composed of a few different subsystems that each work together to produce thrust. The engine is a hybrid, meaning a solid fuel and a liquid oxidizer that allows the fuel to burn. We use a hydroxyl-terminated polybutadiene / nitrous oxide combo. 
> ```

I think this needs a rewrite - I'll send something in a follow-up
___
*[subsystems.html, line 171 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lG3J0M9BGOmTUMnf:-M88lG3J0M9BGOmTUMng:b-45nuj2) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L171)):*
> ```
> <h3>HISTORY</h3>
> ```
Empty?
___
*[subsystems.html, line 174 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88kV_H3JKkPc6QCRv7:-M88kV_H3JKkPc6QCRv8:b-t4b84e) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L174)):*
> ```
> <i>pure ethanol</i>
> ```
this <i> isn't actually doing anything for me

![image copy 1.png](https://files.reviewableuser [...]

2020-05-25 03:07 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 26 of 27 files reviewed, 24 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 304 at r3](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88n4r32_BzJr49KeX5:-M88n4r49xS1heTECgLE:bnnyt5v) ([raw file](https://github.com/waterloo-rocketry/website/blob/fbd19ae88350d98913c399b6f8dbe0a84c6c8bac/subsystems.html#L304)):*
> ```
> Networkx
> ```
NetworkX


<!-- Sent from Reviewable.io -->

2020-05-25 03:56 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 26 of 27 files reviewed, 23 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 65 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hjG7-1I15eK6KOda:-M88nRID1JPA-9mtJBTp:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L65)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> As of 2017
> ```
This makes it sound like the text was last updated in 2017. Maybe "Since 2017" instead?
</blockquote></details>

Done.
___
*[subsystems.html, line 65 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hpopDpQLPj-Okb-5:-M88nTNL0ms-vOnVg80S:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L65)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> its knowledge of composites by manufacturing its
> ```
"our" instead of "its"
</blockquote></details>

Done.
___
*[subsystems.html, line 71 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hyLz-Xfl70tO7nPe:-M88nXj334L3WI4r9Lfv:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L71)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>                         <li>Fiberglass body tubes</li>
>                         <li>Von Kármán fibreglass nose cone</li>
>                         <li>Carbon fibre fin can</li>
> ```
Consistency on "fiber" vs "fibre"?
</blockquote></details>

Done.
___
*[subsystems.html, line 77 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88i3fgEWiYdQ22CTdW:-M88naFr8J1z6s8XiQZ5:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L77)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>  aluminum
> ```
aluminium
</blockquote></details>

Done.
___
*[subsystems.html, line 85 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88i5OA-EdJ0SMn5tAv:-M88ndcN7b4B2nDgsvsL:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L85)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> Watwind
> ```
WatWind
</blockquote></details>

Done.
___
*[subsystems.html, line 85 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88i7KjB_7IOg22VJg5:-M88xpPrA_UwK2XppvD4:b-4epn5b) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L85)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>                         <li>Ox tank aft skirt</li>
>                         <li>Fill disconnect hatch</li>
>                         <li>Composite boattail</li>
>                         <li>Watwind</li>
> ```
This is a bit strange without any other context - I doubt anyone not on the team will know what any of these actually mean.
</blockquote></details>

Asked airframe channel to elaborate 
___
*[subsystems.html, line 95 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88iO5xCESfcUf9KGzf:-M88ngQCDIrH5dnjdTjI:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L95)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> from after apogee (the maximum altitude) to landing
> ```

between apogee (the maximum altitude) and landing
</blockquote></details>

Done.
___
*[subsystems.html, line 98 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88ivDVDqGx0feMLJHE:-M88nmVa4AjdjzL9HEnf:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L98)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> firstly for simplicity and reliability, and secondly for cost, weight, and space savings.
> ```
"primarily for simplicity and reliability, with cost, weight, and space savings as secondary goals."
</blockquote></details>

Done.
___
*[subsystems.html, line 117 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88j2TK4g5cERzj6iIH:-M88npOQ72MUGJ-e5pTf:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L117)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> VIDAR
> ```
Vidar
</blockquote></details>

Done.
___
*[subsystems.html, line 121 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88jm746pTgCoVZySHb:-M88oLxvDjJ2qJFlYpjm:b-n7i6fb) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L121)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> </p>
> ```
Are these necessary?
</blockquote></details>

I thought you needed them to align but nope, took them out 
___
*[subsystems.html, line 135 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88j77e68X2WXIKAnAU:-M88oYcG53CIeBEHhNDW:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L135)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> Space Dynamics Laboratory Payload Challenge at IREC
> ```
Technically the payload challenge is part of the SA Cup, not IREC
</blockquote></details>

Done.
___
*[subsystems.html, line 142 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88jD5D4ANKmW8K1bX6:-M88vjLKA_YCxG05LaNd:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L142)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>                         <li>3U CubeSat</li>
>                         <li>PCBs</li>
>                         <li>software</li>
>                         <li>a different science experiment every year!</li>
> ```
Capitalization

I'm not sure how much this section really adds in the current form, since it's so generic (PCBs? software?). I would suggest making it more specific or removing it altogether.
</blockquote></details>

Done.
___
*[subsystems.html, line 146 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88jZDvEoj4TQ7tCbfS:-M88oon8Cb0nl0-tCO-X:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L146)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> sensor fusion
> ```

just sensor, no fusion
</blockquote></details>

Done.
___
*[subsystems.html, line 150 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88k3VpEf5_7wma5tD5:-M88osY02ZV1oafO7vqJ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L150)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> The plan Payload 2021
> ```
The plan for the 2021 payload
</blockquote></details>

Done.
___
*[subsystems.html, line 150 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lRA-CRDrhvJ-IWKV:-M88sRg6CGr2KkzsZZBL:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc83131 [...]

2020-05-25 04:03 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 26 of 27 files reviewed, 5 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 65 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hpopDpQLPj-Okb-5:-M88zaWHBKlI4O8BxZcq:b-g81l7d) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L65)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You missed one
___
*[subsystems.html, line 95 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88iO5xCESfcUf9KGzf:-M88ziSlCk7Ao_hHK6C3:b3k49cy) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L95)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

after -> between


<!-- Sent from Reviewable.io -->

2020-05-25 04:43 UTC, kylemtam requested changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 26 of 27 files reviewed, 12 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[awards.html, line 25 at r4](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M891PmC-iBnLvH1LLNL:-M891PmC-iBnLvH1LLNM:blvih27) ([raw file](https://github.com/waterloo-rocketry/website/blob/2507e5cb2ea35245687e467f1695a1375d4728ab/awards.html#L25)):*
> ```
> subsystems
> ```
___
*[subsystems.html, line 65 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hpopDpQLPj-Okb-5:-M893LS0CP7p3kTFX2DT:b-udylwj) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L65)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

You missed one
</blockquote></details>

I'd get rid of hand (second last word). I have never seen or heard of an automated layup
___
*[subsystems.html, line 95 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88iO5xCESfcUf9KGzf:-M894Ygc6Xqn276dwPRr:b-fb75oa) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L95)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

after -> between
</blockquote></details>

redundant electronics makes it sound like all the recovery electronics are superfluous. Maybe say 'electronics with built-in redundancies' or something similar?
___
*[subsystems.html, line 161 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lY6e-6EFJFiKJ_MK:-M895B4hAuLB_nPB3I3c:b-9nnjwt) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L161)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I think this needs a rewrite - I'll send something in a follow-up
</blockquote></details>

We should emphasize that we're an engine team and/or the engine is completely student designed and manufactured
___
*[subsystems.html, line 171 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lG3J0M9BGOmTUMnf:-M895PsY9oJn9rlMqlep:br0qes4) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L171)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Yep, messaged the channel to get someone to fill it out
</blockquote></details>

I did some digging evident through my questions in #history tho I wasn't sure how detailed we wanted to go
___
*[subsystems.html, line 251 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8965Fk45nDrxZGiC9B:-M8965Fk45nDrxZGiC9C:b-ojqze6) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L251)):*
> ```HTML
>             </div>
>             <div class = "subsystem_container daq">
>                 <h2 class="content-title">DATA ACQUISITIONS</h2>
> ```

Why is this plural?
___
*[subsystems.html, line 256 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M896OM711ye9J0xoPjL:-M896OM80broe02haf2d:b-kxhh8j) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L256)):*
> ```HTML
>                     <h3>OVERVIEW</h3>
>                     <p>
>                         DAQ, data acquisition, is the system through which engine data is recorded during cold flow and static fire tests. We obtain, monitor and log data from the various sensors attached to the rocket, including load cells, pressure transducers, and thermistors. This subsystem covers the entire chain from calibrating the sensors to connecting the various cables and wires to writing the computer code to process the data.
> ```

Should Data Acquisition be capitalized? 
___
*[subsystems.html, line 257 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M896JxgCUIAV3as3d3H:-M896JxgCUIAV3as3d3I:b-xlvetu) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L257)):*
> ```HTML
>                     <p>
>                         DAQ, data acquisition, is the system through which engine data is recorded during cold flow and static fire tests. We obtain, monitor and log data from the various sensors attached to the rocket, including load cells, pressure transducers, and thermistors. This subsystem covers the entire chain from calibrating the sensors to connecting the various cables and wires to writing the computer code to process the data.
>                         Although DAQ is mostly used during engine tests in Waterloo, a version of the system travels to competition along with the rocket. It is used together with RLCS to provide live data during the launch.
> ```

travels with us to competition
___
*[subsystems.html, line 283 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M896ytlEiITmjFP1BWt:-M896ytlEiITmjFP1BWu:b-tvnn29) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L283)):*
> ```HTML
>                     <h3>OVERVIEW</h3>
>                     <p>
>                         RLCS, the Remote Launch Control System, is responsible for allowing remote control of the ground based plumbing, and enabling communication between Mission Control and the rocket’s on board flight computers. This means that it allows the rocket to be fuelled and launched remotely and from a safe distance.
> ```

on-board. 'on board' is used as a prepositional phrase (e.g. he was on board the plane). 'on-board' is an adjective
___
*[subsystems.html, line 294 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M897W5cCVYx3HEI_JZ8:-M897W5cCVYx3HEI_JZ9:bwbyfzu) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L294)):*
> ```HTML
>                     <h3>HISTORY</h3>
>                     <p>
>                         As our rockets have become larger, and as we focused more on safety, we required a remote system for controlling our rockets. The initial RLCS consisted of four or five different boxes, and was far from robust. The second version operated as described above and was almost completely redesigned, with a major emphasis being placed on robustness, and has successfully been used for three years, including two launches and countless tests.   
> ```

Should the commas before the ands be included, especially:
', and was far from robust'

The last sentence also sounds like a run-on sentence. Split it into two?
___
*[subsystems.html, line 71 at r4](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M893ph826bExJRpnpEk:-M893ph826bExJRpnpEl:bfvrqd) ([raw file](https://github.com/waterloo-rocketry/website/blob/2507e5cb2ea35245687e467f1695a1375d4728ab/subsystems.html#L71)):*
> ```HTML
>                     <li>Von Kármán fibreglass nose cone</li>
>                     <li>Carbon fibre fin can</li>
>                     <li>Aluminium oxidizer tank</li>
> ```

Aluminum


<!-- Sent from Reviewable.io -->

2020-05-25 04:48 UTC, kylemtam reviewed
Two general comments:
- Payload in the drawing is in the wrong spot. It should be right underneath recovery
- Recovery should encompase both the nosecone and the first body tube section

- Maybe it's a Firefox thing but once I click a new subsystem, it automatically scrolls me up to the top of the page. But after that if I click another subsystem, it no longer scrolls me up anymore. Not a big issue, just eyebrow-raising

2020-05-25 05:10 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 24 of 27 files reviewed, 12 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[awards.html, line 25 at r4](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M891PmC-iBnLvH1LLNL:-M89DQc0-Y-5F_YgK_R5:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/2507e5cb2ea35245687e467f1695a1375d4728ab/awards.html#L25)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

> ```
> subsystems
> ```

</blockquote></details>

Done.
___
*[subsystems.html, line 65 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88hpopDpQLPj-Okb-5:-M89-Qmy-JO-qRcIkuYL:bys9x2q) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L65)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

I'd get rid of hand (second last word). I have never seen or heard of an automated layup
</blockquote></details>

:c aa oops sorry thanks (Jacob)
and done (Kyle)
___
*[subsystems.html, line 161 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lY6e-6EFJFiKJ_MK:-M89Bkyt0gctG1x9a9fa:bq84tr9) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L161)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

We should emphasize that we're an engine team and/or the engine is completely student designed and manufactured
</blockquote></details>

Done - Jacob rewrote this and sent it on Slack, though I hadn't pushed the changes yet.
___
*[subsystems.html, line 171 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lG3J0M9BGOmTUMnf:-M89D49u4CVwpO-16GuH:b-wot4cw) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L171)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

I did some digging evident through my questions in #history tho I wasn't sure how detailed we wanted to go
</blockquote></details>

Doesn't have to be huge I don't think, the other sections are usually two or three sentences.
___
*[subsystems.html, line 251 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8965Fk45nDrxZGiC9B:-M89BuYk2BYo-BKcQbP9:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L251)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Why is this plural?
</blockquote></details>

Done.
___
*[subsystems.html, line 256 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M896OM711ye9J0xoPjL:-M89BxBq-sSLQtDz5FCe:bcxvbg7) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L256)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Should Data Acquisition be capitalized? 
</blockquote></details>

I don't think so? None of the other subteams are, I don't think it's a proper noun in its own right. 

Also personal pet peeve but I hate unnecessary capitalization it gives me rage and anger :)
___
*[subsystems.html, line 257 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M896JxgCUIAV3as3d3H:-M89D01AD0GF3K4pAQmY:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L257)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

travels with us to competition
</blockquote></details>

Done.
___
*[subsystems.html, line 283 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M896ytlEiITmjFP1BWt:-M89CRZY8ThUzlJ2ShvK:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L283)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

on-board. 'on board' is used as a prepositional phrase (e.g. he was on board the plane). 'on-board' is an adjective
</blockquote></details>

Done.
___
*[subsystems.html, line 294 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M897W5cCVYx3HEI_JZ8:-M89CUuL7fFASUsqAtoc:b-8q55hm) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L294)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Should the commas before the ands be included, especially:
', and was far from robust'

The last sentence also sounds like a run-on sentence. Split it into two?
</blockquote></details>

I think the comma is fine, it follows the natural flow of the sentence pretty well. I agree on the last sentence though, I'll split it.
___
*[subsystems.html, line 71 at r4](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M893ph826bExJRpnpEk:-M89Akp77Un4Kzr-ENxv:bvc3lxq) ([raw file](https://github.com/waterloo-rocketry/website/blob/2507e5cb2ea35245687e467f1695a1375d4728ab/subsystems.html#L71)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Aluminum
</blockquote></details>

Apparently "aluminium" is the scientific standard, if you and Jacob want to turf it out :) Looks like the ISO prefers aluminium and various American societies prefer aluminum.


<!-- Sent from Reviewable.io -->

2020-05-25 05:20 UTC, wendi-yu commented
Yeah, the scrolling happens to me too. I've tried many many fixes but none of them seem to work :( this seems like a common issue on StackOverflow that rarely gets resolved. I'll try some more but I think that might be a next-PR issue?

2020-05-25 06:12 UTC, kylemtam reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 23 of 27 files reviewed, 13 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 263 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M89SNm3E48szqlkBYgs:-M89SNm3E48szqlkBYgt:b-pesjst) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L263)):*
> ```HTML
>                         <li>LabView</li>
>                         <li>Data Acquisition PCB</li>
>                         <li>NI-DAQ Module</li>
> ```

If that's the case for capitalization, then Acquisition and Module should not be capitalized then. Just wanted to be consistent in this section. Also it's LabVIEW


<!-- Sent from Reviewable.io -->

2020-05-25 06:15 UTC, kylemtam reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 23 of 27 files reviewed, 8 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 71 at r4](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M893ph826bExJRpnpEk:-M89Sp730p_Wur-btFaS:b-fmva1) ([raw file](https://github.com/waterloo-rocketry/website/blob/2507e5cb2ea35245687e467f1695a1375d4728ab/subsystems.html#L71)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Apparently "aluminium" is the scientific standard, if you and Jacob want to turf it out :) Looks like the ISO prefers aluminium and various American societies prefer aluminum.
</blockquote></details>

Generally Americans say aluminum and Brits say aluminium. Canada usually says it aluminum - also consider the target audience isn't necessary someone super technical so aluminum is more in line with the general public in my opinion


<!-- Sent from Reviewable.io -->

2020-05-25 06:21 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 23 of 27 files reviewed, 8 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 263 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M89SNm3E48szqlkBYgs:-M89ULTFDEl-2Wn1iU4t:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L263)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

If that's the case for capitalization, then Acquisition and Module should not be capitalized then. Just wanted to be consistent in this section. Also it's LabVIEW
</blockquote></details>

Done.
___
*[subsystems.html, line 71 at r4](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M893ph826bExJRpnpEk:-M89U-pODmvQ8vOBgUuq:bnrgemz) ([raw file](https://github.com/waterloo-rocketry/website/blob/2507e5cb2ea35245687e467f1695a1375d4728ab/subsystems.html#L71)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Generally Americans say aluminum and Brits say aluminium. Canada usually says it aluminum - also consider the target audience isn't necessary someone super technical so aluminum is more in line with the general public in my opinion
</blockquote></details>

Hmm ok let's see if Jacob wants to chime in in the morning, I'll leave this for tonight


<!-- Sent from Reviewable.io -->

2020-05-25 17:57 UTC, jacobdeery approved these changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 23 of 27 files reviewed, 6 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 71 at r4](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M893ph826bExJRpnpEk:-M8BxjBgD_jdSODgxT3q:b6quv13) ([raw file](https://github.com/waterloo-rocketry/website/blob/2507e5cb2ea35245687e467f1695a1375d4728ab/subsystems.html#L71)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Hmm ok let's see if Jacob wants to chime in in the morning, I'll leave this for tonight
</blockquote></details>

Our technical reports have used and should continue to use the IUPAC recommended spelling of "aluminium". My preference and recommendation is to use this spelling everywhere for consistency, but ultimately I won't block for it. Whichever spelling you choose, please ensure in a follow-up PR that it's consistent across the whole website (excluding the reports, if you decide to use "aluminum").


<!-- Sent from Reviewable.io -->

2020-05-25 18:07 UTC, kylemtam approved these changes
- I agree with Jacob's comment.

- I think the propulsion image highlighting is slightly misleading as it's currently highlighting just the ox tank and fire (nothing on the combustion chamber and it's debatable whether we should highlight vent and injector for propulsion as well) but I think this page is at a good enough point to merge. We can raise other minor issues at a later date

2020-05-26 01:02 UTC, wendi-yu reviewed
Cool, I'll stick with aluminium for the sake of consistency. Followup PR to come, if I can `grep` out any aluminums floating around the site.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107#-:-M8DRfJd4v07s0u8WGYG:b-8zkx4h)* status: 23 of 27 files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @kylemtam)

___
*[subsystems.html, line 85 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88i7KjB_7IOg22VJg5:-M8DRrtiBC8ccU49nFHZ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L85)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Asked airframe channel to elaborate 
</blockquote></details>

Done.
___
*[subsystems.html, line 171 at r2](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M88lG3J0M9BGOmTUMnf:-M8DRtsL7Vn6Rfj5q5ny:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/9edb6149911cc8313166fa03493ada11ae9c4a02/subsystems.html#L171)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Doesn't have to be huge I don't think, the other sections are usually two or three sentences.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-26 01:50 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 7 of 27 files reviewed, 12 unresolved discussions (waiting on @jacobdeery, @kylemtam, and @wendi-yu)

___
*[subsystems.html, line 87 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8Ddqvv4SpQYLirXNwG:-M8Ddqvv4SpQYLirXNwH:b-ucrvxh) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L87)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>                         <li>Ox tank aft skirt: the structure between the oxidizer tank and the engine. It houses the injector valve and rocket side fill plumbing.</li>
>                         <li>Fill disconnect hatch: an access panel on the rocket that opens to accommodate tower side fill plumbing and closes after fill disconnect system actuation.</li>
>                         <li>Composite boattail: a lighter and more aerodynamic version of the old aluminium boattail that used to double as a heat sink for the engine.</li>
>                         <li>Composites stress calculator: A calculator implemented in Python to aid in composites layup schedule design by calculating stress in each ply.</li>
>                         <li>WatWind: a 3-axis filament winder for use in manufacturing of body tubes.</li>
>                         <li>Nosecone mould: Female fibreglass mould to replace aging <a href="https://en.wikipedia.org/wiki/Medium-density_fibreboard" target="_blank">MDF</a> moulds used in the nosecone layup process.</li>
> ```
</details>

inconsistent capitalization after colon
___
*[subsystems.html, line 97 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DdtbC53EXdXuD3q2P:-M8DdtbC53EXdXuD3q2Q:b7tf798) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L97)):*
> ```
> from between
> ```
missed this earlier, sorry: just "between", no "from"
___
*[subsystems.html, line 119 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DdzeP7zmkJOHJCEmH:-M8DdzeP7zmkJOHJCEmI:bwk7ssv) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L119)):*
> ```
> ·
> ```
trailing whitespace
___
*[subsystems.html, line 119 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8De72DBT2yjzIaMaNP:-M8De72E1-NK7IiUVB89:b-wlwq02) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L119)):*
> ```
> For the past 3 years we have had partial successes with our recovery system, where our drogue chute deploys correctly, but our main parachute fails to deploy.
> ```
In each of our past 3 flights, our drogue chute has deployed correctly but the main parachute has failed to deploy.
___
*[subsystems.html, line 149 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DehbI4LZ8sr8q2R_F:-M8DehbI4LZ8sr8q2R_G:b-5gf5ck) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L149)):*
> ```
> nanotubes
> ```
should be singular, right?
___
*[subsystems.html, line 173 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DerUm2CnYyRgxEtWP:-M8DerUm2CnYyRgxEtWQ:b-e6gpk9) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L173)):*
> ```
> apogee target
> ```
target apogee
___
*[subsystems.html, line 179 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8Df1wFASh-fqMHa7kD:-M8Df1wFASh-fqMHa7kE:b-vrz0ua) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L179)):*
> ```
> with the MSAM
> ```
with MSAM
___
*[subsystems.html, line 315 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DfBTiCMcxJ8sPYEyz:-M8DfBTiCMcxJ8sPYEz-:bwk7ssv) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L315)):*
> ```
> ·
> ```
trailing whitespace


<!-- Sent from Reviewable.io -->

2020-05-26 03:34 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 6 of 27 files reviewed, 12 unresolved discussions (waiting on @jacobdeery and @kylemtam)

___
*[subsystems.html, line 87 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8Ddqvv4SpQYLirXNwG:-M8E-c_R86xz8gCMSf39:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L87)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>                         <li>Ox tank aft skirt: the structure between the oxidizer tank and the engine. It houses the injector valve and rocket side fill plumbing.</li>
>                         <li>Fill disconnect hatch: an access panel on the rocket that opens to accommodate tower side fill plumbing and closes after fill disconnect system actuation.</li>
>                         <li>Composite boattail: a lighter and more aerodynamic version of the old aluminium boattail that used to double as a heat sink for the engine.</li>
>                         <li>Composites stress calculator: A calculator implemented in Python to aid in composites layup schedule design by calculating stress in each ply.</li>
>                         <li>WatWind: a 3-axis filament winder for use in manufacturing of body tubes.</li>
>                         <li>Nosecone mould: Female fibreglass mould to replace aging <a href="https://en.wikipedia.org/wiki/Medium-density_fibreboard" target="_blank">MDF</a> moulds used in the nosecone layup process.</li>
> ```
inconsistent capitalization after colon
</blockquote></details>

Done.
___
*[subsystems.html, line 97 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DdtbC53EXdXuD3q2P:-M8E-nT0AefmhSkRUjZz:b-n7dcyn) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L97)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> from between
> ```
missed this earlier, sorry: just "between", no "from"
</blockquote></details>

lmao I'm so bad at this line, done
___
*[subsystems.html, line 119 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DdzeP7zmkJOHJCEmH:-M8E01_79_1ebBnqGOpP:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L119)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ·
> ```
trailing whitespace
</blockquote></details>

Done.
___
*[subsystems.html, line 119 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8De72DBT2yjzIaMaNP:-M8E05X-3G6RFU1vWq2X:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L119)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> For the past 3 years we have had partial successes with our recovery system, where our drogue chute deploys correctly, but our main parachute fails to deploy.
> ```
In each of our past 3 flights, our drogue chute has deployed correctly but the main parachute has failed to deploy.
</blockquote></details>

Done.
___
*[subsystems.html, line 149 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DehbI4LZ8sr8q2R_F:-M8E064M-1QLsqZahXhn:bj62e0c) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L149)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> nanotubes
> ```
should be singular, right?
</blockquote></details>

Wikipedia says singular but the bnnt website is plural, I think in this context singular makes sense though
___
*[subsystems.html, line 173 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DerUm2CnYyRgxEtWP:-M8E0W8439TzOEg2EsPa:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L173)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> apogee target
> ```
target apogee
</blockquote></details>

Done.
___
*[subsystems.html, line 179 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8Df1wFASh-fqMHa7kD:-M8E0Xif6IHc6tQSQjfH:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L179)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> with the MSAM
> ```
with MSAM
</blockquote></details>

Done.
___
*[subsystems.html, line 315 at r6](https://reviewable.io/reviews/waterloo-rocketry/website/107#-M8DfBTiCMcxJ8sPYEyz:-M8E0_Kf-laBK5IoHivF:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website/blob/563ac30d3a6fd00e0b71c595799b52bdbaace2bd/subsystems.html#L315)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ·
> ```
trailing whitespace
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-26 03:39 UTC, jacobdeery approved these changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website/107)* status: 6 of 27 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @kylemtam)



<!-- Sent from Reviewable.io -->

2020-05-26 03:41 UTC, merged