Added the most recent award to the Award page
amihaila/wrt-site pull request #48
Opened 2018-06-30 13:51 UTC by AidanHa

Also Categorized awards based on year.

2018-06-30 14:05 UTC, jacobdeery requested changes

2018-06-30 14:05 UTC, jacobdeery commented on awards.html
> +								The Category First Place Awards recognize the teams with the highest overall scores in each of the six competition categories. Teams are scored on the project technical report, competency of
change last sentence to "[...] at the 2018 IREC, with the debut flight of UXO."

2018-06-30 15:05 UTC, amihaila requested changes
Can you make the text for "2017" and "2018" smaller? Right now it has font weight 600 and size 3 rem. I'd suggest weight 300 and size 2 rem to be more in line with the rest of the site.

2018-06-30 15:13 UTC, jacobdeery commented
I would suggest wrapping the year headers with `content-title` and then scaling the award title headers down to something smaller.

2018-06-30 17:01 UTC, amihaila requested changes

2018-06-30 17:01 UTC, amihaila commented on awards.html
> +				<h3 class="content-title" style="font-size: 2.0rem">2018</h3>
Can you make the font changes in css/awards.css instead of directly in the html? It's a bit easier to maintain.

The reason I suggested specific font weights/sizes was so that they match the weights/sizes on the rocket pages (eg. "2018" should match "Vidar III" and the award titles should match the subsystem titles). It's just good to be consistent.

2018-06-30 18:01 UTC, AidanHa commented on awards.html
> +				<h3 class="content-title" style="font-size: 2.0rem">2018</h3>
I moved all of the css to the .css file.  Making the 2018 match "Vidar III" didn't look great at all, so I added new css and changed the titles to be "h2"

2018-06-30 18:10 UTC, amihaila commented on awards.html
> +				<h3 class="content-title" style="font-size: 2.0rem">2018</h3>
I'm confused - the most recent commit I pulled has the "2018" text matching "Vidar III" (from waterloorocketry.com/vidar3.html).

2018-06-30 18:14 UTC, AidanHa commented on awards.html
> +				<h3 class="content-title" style="font-size: 2.0rem">2018</h3>
Oh my fault, I misunderstood what you were saying and thought you were referring to "Vidar III" from the awards page. But yes, the 2018 is now matching "Vidar III" from  waterloorocketry.com/vidar3.html

2018-06-30 18:21 UTC, amihaila approved these changes

2018-07-01 00:23 UTC, jacobdeery requested changes
I know you didn't introduce this typo, but let's fix it while we have the chance.

2018-07-01 00:23 UTC, jacobdeery commented on awards.html
> +						<h2>10K LIQUID/HYBRID STUDENT RESEARCH AND DEVELOPED</h2>
Just noticed this now. Should be "RESEARCHED", not "RESEARCH". I guess it's been like that for over a year?

2018-07-01 00:28 UTC, jacobdeery approved these changes

2018-07-01 01:04 UTC, thatfellarobin requested changes
change the award titles to “FIRST PLACE - 10K LIQUID/HYBRID SRAD” for both 2017 and 2018, and then add a short explanation of the category in the award description.

2018-07-01 03:41 UTC, jacobdeery requested changes

2018-07-01 03:41 UTC, jacobdeery commented on awards.html
> +								The Category First Place Awards recognize the teams with the highest overall scores in each of the six competition categories. Teams are scored on the project technical report, competency of
Wording here is awkward. I would change "degree of SRAD" to "degree of student development" and find a better way to work the explanation of SRAD into the description.

2018-07-01 03:41 UTC, jacobdeery commented on awards.html
> +								The Category First Place Awards recognize the teams with the highest overall scores in each of the six competition categories. Teams are scored on the project technical report, competency of
Same comment as above.

2018-07-01 13:23 UTC, thatfellarobin commented on awards.html
> +								The Category First Place Awards recognize the teams with the highest overall scores in each of the six competition categories. Teams are scored on the project technical report, competency of
Take Jacob's suggestion, and change the first sentence to "The Category First Place Awards recognize the teams with the highest overall scores in each of the six competition categories, with this category representing Student Researched and Developed (SRAD) Hybrid/Liquid engines targeting an apogee of 10000 feet."

2018-07-02 15:56 UTC, jacobdeery approved these changes

2018-07-03 18:04 UTC, thatfellarobin approved these changes

2018-07-03 23:59 UTC, merged