Update cover page photos (main and rocket)
amihaila/wrt-site pull request #54
Opened 2018-07-05 00:04 UTC by amihaila

2018-07-05 19:27 UTC, jacobdeery commented
Looks good. Do we want to feature creep this PR even more and change the other two cover page photos?

2018-07-05 19:27 UTC, amihaila commented
Feature creep is my jam. Gimme a sec.

2018-07-06 21:01 UTC, jacobdeery requested changes
IMO the cover photo for "Rockets" should be named "rockets_cover", not "uxo_cover"

2018-07-06 21:18 UTC, jacobdeery approved these changes

2018-07-06 21:21 UTC, closed without merging