UXO page
amihaila/wrt-site pull request #61
Opened 2018-08-22 13:13 UTC by AidanHa

Added UXO page. Please review over the content of the page. Also, I left the drawing/picture out on the uxo page since all of the pictures that I tried to put looked really off.

2018-08-22 13:31 UTC, akmorrison1 commented on uxo.html
> +						polybutadiene SRAD(Student Researched and Designed) hybrid engine, and achieved a successful launch and recovery, at the 2018 IREC.
We did not achieve a successful recovery

2018-08-22 13:42 UTC, jacobdeery requested changes

2018-08-22 13:42 UTC, jacobdeery commented on rockets.html
> +							<h1 class="title">UXO</h1>
We should probably use the full name of the rocket here

2018-08-22 13:42 UTC, jacobdeery commented on rockets.html
> +							<h1 class="title">2017/2018</h1>
Just 2018. The reason Vidar III is 2016/2017 is because it went to two competitions.

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +		<title>UXO - Waterloo Rocketry</title>
Unexploded Ordnance

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +					UXO
Unexploded Ordnance

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +						polybutadiene SRAD(Student Researched and Designed) hybrid engine, and achieved a successful launch and recovery, at the 2018 IREC.
Remove "(Student Researched and Designed)", since we've already explained the acronym. Also, remove the last comma (before "at the 2018 IREC")

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +				<h1 class="content-title">SPECS<h1>
I would also add motor classification (O) and wet mass (141 lb); see Vidar III for where to put them

2018-08-22 13:42 UTC, jacobdeery commented on css/rockets.css
> +	background: url('../images/uxo.jpg');
We already used this picture (for the "Rockets" image on the homepage). We should change one of them.

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +						mechanism, which would promote future iteration and development of scientific payloads.	CubeSat, an instrument package
"CubeSat" isn't the name of the instrument package, it's the form factor.

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +							 the creation of a 2-part mold CNC-machined from medium-density fiberboard,
This sentence ends with a comma. Was there meant to be more content, or should it be a period?

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +						This component houses the rocket's solid fuel and it is also made of 6061-T6 aluminum. The combustion chamber
aluminum -> aluminium. Normally I wouldn't care unless it's a report that we're submitting, but we've used aluminium everywhere else on this page, so let's be consistent.

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +						The fuel used in Kismet is a mixture of HTPB and powdered aluminium by mass, and has a pseudo-finocyl grain geometry
"a mixture of 90% HTPB and 10% powdered aluminium by mass"

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +							UXO uses a fin can assembly of three through-the-wall trapezoidal fins welded to 6” OD, 13” long, 1/4” thick
Our fins aren't through-the-wall, are they? They're welded to a can. I think through-the-wall only applies if the fins physically stick through the airframe.

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +					<img src="https://farm1.staticflickr.com/840/42483288184_376d6ab1e0_o_d.jpg">
We already used this picture

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +					<h1 class="content-title">AVIONICS</h1>
Combine this section with "RECOVERY MODULE" and just call it "RECOVERY".

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +						is insulated with a 1/8” thick G10 fiberglass tube and sealed with flame-resistant caulking on the top and bottom ends.
” -> "

2018-08-22 13:42 UTC, jacobdeery commented on uxo.html
> +							UXO uses a fin can assembly of three through-the-wall trapezoidal fins welded to 6” OD, 13” long, 1/4” thick
Also, ” -> "

2018-08-27 01:56 UTC, AidanHa commented on uxo.html
> +							UXO uses a fin can assembly of three through-the-wall trapezoidal fins welded to 6” OD, 13” long, 1/4” thick
What do you want me to fix with " -> "

2018-08-27 02:02 UTC, AidanHa commented on uxo.html
> +							UXO uses a fin can assembly of three through-the-wall trapezoidal fins welded to 6” OD, 13” long, 1/4” thick
oh, indenting

2018-08-27 02:09 UTC, jacobdeery commented on uxo.html
> +							UXO uses a fin can assembly of three through-the-wall trapezoidal fins welded to 6” OD, 13” long, 1/4” thick
I mean the literal `”` that you have in `6” OD, 13” long, 1/4” thick`. Those should be `"` instead.

2018-08-31 15:55 UTC, akmorrison commented on css/rockets.css
> +	/*background: url('http://c2.staticflickr.com/4/3674/18709120553_a3c3db48e4_b.jpg');*/
It looks like this comment was just copy pasted over, is there a reason it’s here?

2018-08-31 16:18 UTC, AidanHa commented on css/rockets.css
> +	/*background: url('http://c2.staticflickr.com/4/3674/18709120553_a3c3db48e4_b.jpg');*/
There's actually no reason for the comment, I'll just remove it for the next push

2018-08-31 16:30 UTC, AidanHa commented on uxo.html
> +					<h1 class="content-title">AVIONICS</h1>
How exactly should I combine this section with "RECOVERY"? I think it might look better if we have 2 separate sections

2018-09-01 00:17 UTC, jacobdeery commented on uxo.html
> +						 the creation of a 2-part mold CNC-machined from a medium-density fiberboard.
You were actually correct the first time (without the "a"). MDF is the material; the mold wasn't machined from a single board.

2018-09-01 00:17 UTC, jacobdeery commented on uxo.html
> +						in the 10000 ft apogee with a SRAD hybrid/liquid
This "SRAD" should have "(Student Researched and Developed)" after it

2018-09-01 00:17 UTC, jacobdeery commented on uxo.html
> +						polybutadiene SRAD(Student Researched and Designed) hybrid engine, and achieved a successful launch at the 2018 IREC.
This "SRAD" should have nothing after it.

2018-09-01 00:24 UTC, jacobdeery commented on uxo.html
> +					<h1 class="content-title">AVIONICS</h1>
I think this looks good

![image](https://user-images.githubusercontent.com/13474696/44940391-ce536080-ad5b-11e8-93fe-bac67d36eb18.png)

2018-09-01 00:28 UTC, jacobdeery commented on uxo.html
> +						The UXO recovery system consists of a drogue parachute and main parachute housed  in two adjacent fiberglass
There's an extra space after "housed"

2018-09-01 00:28 UTC, jacobdeery commented on uxo.html
> +						reliability of the system.	Each altimeter is capable of independently triggering each ejector and each cutter.
There's a tab instead of a space after "system."

2018-09-01 00:28 UTC, jacobdeery commented on uxo.html
> +				<h1 class="content-title">DETAILS</h1>
Something strange is going on here for me. The "DETAILS" header is showing up immediately after the main chute diameter, not left-aligned.

![image](https://user-images.githubusercontent.com/13474696/44940409-09559400-ad5c-11e8-9ea7-6fd1d2378f6a.png)

2018-09-01 00:28 UTC, jacobdeery commented on rockets.html
> +							<h1 class="title">Unexploded Ordnance</h1>
"UNEXPLODED ORDNANCE" (all caps). My mistake, I should have made that more clear earlier during my first review.

2018-09-01 00:28 UTC, jacobdeery commented on uxo.html
> +					Unexploded Ordnance
"UNEXPLODED ORDNANCE" (all caps).

2018-09-01 05:21 UTC, AidanHa commented on uxo.html
> +				<h1 class="content-title">DETAILS</h1>
Yea, something weird with the BootStrap here. I did a temporary fix by moving some information from the right column to the left.

2018-09-03 21:11 UTC, jacobdeery approved these changes

2018-09-03 21:14 UTC, merged